### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Steve0212a** [drasticactions/Drastic.Tools#2]
I have been looking for something like this to run in Catalyst for a while (basically a Windows like system tray app with a drop down window).  I have not had time yet to review all the code, so forgive me if some of my questions are obvious.

Questions:

1. When I run Drastic.Tray.NoDock.Sample.Catalyst, an extra window is opened.  I do not want that.  Is it possible to only have the tray icon and the drop down tray window while using Maui and Catalyst?
2. You also have Drastic.Tray.NoDock.Sample.Mac.  What is this?  It was my understanding the Maui could only use Catalyst?  This appears to fix the "extra window" issue of catalyst.  Any documentation you could point me to would be much appreciated.

Thanks for doing this project.  It is VERY hard to find good info on Maui and Catalyst...

**Comment by Steve0212a** [comment]
Actually, I am going to guess that the mac app is this - correct?

![image](https://user-images.githubusercontent.com/18215939/233166893-89a68440-f3ec-434d-a0eb-a5650159f6ba.png)

**Comment by Rjvs** [comment]
This isn't really a forum to ask questions without reading the code; I'm sure you want to save Tim's attention in case you run up against a real problem, so I'll jump in and answer so that the issue can be closed.

There's a "native" MacOS implementation and a Mac Catalyst implementation, you can choose which to use.  I presume that the main difference is going to be the controls that have been implemented in MAUI for each platform but I don't know what the practical implications are; you can experiment and let us know.

You don't have to open any windows that you don't want to, this is an example/proof of concept, you should change the code so it does what you want.
